### PR TITLE
Custom cooldown percentage for critical hits + Double shield countering

### PR DESCRIPTION
**Pull request by sootysplash**
Added a setting so you can choose at what cooldown percentage it will perform a critical hit (you don't need to be at 100% cooldown to do one) + made the axe double click when disabling a shield, to perform a stun which deals extra knockback, I've tested this with dynamic/constant click modes and I've seen no conflicts

### CODE REVIEW

**Comment by Sumandora** [comment]
Regarding the critical hit cooldown: It is true that performing criticals with lower attack cooldown is possible, however criticals work by multiplying your baseDamage with 1.5 however, since your cooldown wasn't finished the baseDamage will be rather low. The way you implemented this is by simply ignoring the real delay, which might felt better during testing, because it simply hits more often and that usually translates to more dominance over an opponent. However this means that the configurable attack cooldown would have to be implemented at the ClickSpeedUtil, which is something I am planning to do, but haven't found a proper solution since I would prefer to have a proper system that allows ClickMethods to have settings. Another idea would be to rewrite the KillAura into a "Minimum damage"-driven model, however that might be annoying to configure for each weapon. All in all I am aware of the issue but I don't think this PR would solve it.

Regarding the shield blocking: I am unsure if I am interpreting the code wrong, but the second hit you are forcing would probably not change the previous behavior, because your hurt time would be != 0, so you can't hit the opponent. If I am misinterpreting this, please correct me.

I won't merge this for now since I can't see the value gained by it and/or I have plans to implement these features better

**Comment by FDPUser443** [comment]
Hey, the problem is that one of the requirements to perform a critical hit is "A base attack must not be reduced below 90% damage due to cooldown.‌" (according to https://minecraft.fandom.com/wiki/Damage), isn't it?

**Comment by Sumandora** [comment]
> Hey, the problem is that one of the requirements to perform a critical hit is "A base attack must not be reduced below 90% damage due to cooldown.‌" (according to https://minecraft.fandom.com/wiki/Damage), isn't it?

I didn't know about the condition but yeah, that seems to be another reason why this wouldn't work

**Comment by Sumandora** [comment]
Closing as stale

**Pull request closed without merging**
